// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEQfKmWHwxluCv1cTgDdOfPPf7WNle8n0',
    appId: '1:258077766704:web:492155e806fc65548a29f5',
    messagingSenderId: '258077766704',
    projectId: 'tinder-c2ca6',
    authDomain: 'tinder-c2ca6.firebaseapp.com',
    storageBucket: 'tinder-c2ca6.firebasestorage.app',
    measurementId: 'G-W4GT5VW687',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEXOYvgtmOUKMDGeLqna7YlubS6TNVKA4',
    appId: '1:258077766704:android:4bc644f31b4d0e918a29f5',
    messagingSenderId: '258077766704',
    projectId: 'tinder-c2ca6',
    storageBucket: 'tinder-c2ca6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFYbhGznrnaf1zv_HQJXi5uIytuRy84pk',
    appId: '1:258077766704:ios:b5b41c9f8a73a0438a29f5',
    messagingSenderId: '258077766704',
    projectId: 'tinder-c2ca6',
    storageBucket: 'tinder-c2ca6.firebasestorage.app',
    androidClientId: '258077766704-hps5thkgbd59ccrd72tcsbgln2utigjc.apps.googleusercontent.com',
    iosClientId: '258077766704-klokj23u335t9dg4jt5ignnjm5pbrje6.apps.googleusercontent.com',
    iosBundleId: 'com.example.tinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFYbhGznrnaf1zv_HQJXi5uIytuRy84pk',
    appId: '1:258077766704:ios:b5b41c9f8a73a0438a29f5',
    messagingSenderId: '258077766704',
    projectId: 'tinder-c2ca6',
    storageBucket: 'tinder-c2ca6.firebasestorage.app',
    iosBundleId: 'com.example.tinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEQfKmWHwxluCv1cTgDdOfPPf7WNle8n0',
    appId: '1:258077766704:web:94e196d60218acec8a29f5',
    messagingSenderId: '258077766704',
    projectId: 'tinder-c2ca6',
    authDomain: 'tinder-c2ca6.firebaseapp.com',
    storageBucket: 'tinder-c2ca6.firebasestorage.app',
    measurementId: 'G-CNTT7115PN',
  );

}